#!/bin/sh

# Cleanup previous simulation data
rm -rf obj_dir
rm -f pc_top.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --top-module pc_top pc_top.sv pc_next.sv pc_plus.sv pc_target.sv --exe pc_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpc_top.mk Vpc_top

# Run executable simulation file
obj_dir/Vpc_top