# cleanup
rm -rf obi_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp

# build c++ project via make automatically generated by Verilator

make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation 
obj_dir/Vtop